#pragma once

// From glfw3.h
#define USAGI_MOUSE_BUTTON_1         0
#define USAGI_MOUSE_BUTTON_2         1
#define USAGI_MOUSE_BUTTON_3         2
#define USAGI_MOUSE_BUTTON_4         3
#define USAGI_MOUSE_BUTTON_5         4
#define USAGI_MOUSE_BUTTON_6         5
#define USAGI_MOUSE_BUTTON_7         6
#define USAGI_MOUSE_BUTTON_8         7
#define USAGI_MOUSE_BUTTON_LAST      USAGI_MOUSE_BUTTON_8
#define USAGI_MOUSE_BUTTON_LEFT      USAGI_MOUSE_BUTTON_1
#define USAGI_MOUSE_BUTTON_RIGHT     USAGI_MOUSE_BUTTON_2
#define USAGI_MOUSE_BUTTON_MIDDLE    USAGI_MOUSE_BUTTON_3